# Generated by Django 5.0.4 on 2024-04-27 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_shortenedurl_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortenedurl',
            name='short_code',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
